import { supabase } from '../lib/supabase.js';

export async function listDrivers({branchId=null,activeOnly=false}={}){let q=supabase.from('delivery_drivers').select('*, branches(name)').order('name');if(branchId)q=q.eq('branch_id',branchId);if(activeOnly)q=q.eq('is_active',true);const {data,error}=await q;if(error)throw error;return data||[];}
export const listDeliveryDrivers = listDrivers;
export async function createDriver(p){const {data,error}=await supabase.from('delivery_drivers').insert(p).select().single();if(error)throw error;return data;}
export const createDeliveryDriver=createDriver;
export async function updateDriver(id,p){const {data,error}=await supabase.from('delivery_drivers').update(p).eq('id',id).select().single();if(error)throw error;return data;}
export const updateDeliveryDriver=updateDriver;
export async function deleteDriver(id){const {error}=await supabase.from('delivery_drivers').delete().eq('id',id);if(error)throw error;}
export const deleteDeliveryDriver=deleteDriver;
export async function listDriverTransactions({driverId,branchId=null,from=null,to=null}={}){let q=supabase.from('driver_transactions').select('*, branches(name), profiles(full_name)').eq('driver_id',driverId).order('txn_date',{ascending:false}).order('created_at',{ascending:false});if(branchId)q=q.eq('branch_id',branchId);if(from)q=q.gte('txn_date',from);if(to)q=q.lte('txn_date',to);const {data,error}=await q;if(error)throw error;return data||[];}
export async function createDriverTransaction(payload){const {data,error}=await supabase.from('driver_transactions').insert(payload).select().single();if(error)throw error;return data;}
export async function deleteDriverTransaction(id){const {error}=await supabase.from('driver_transactions').delete().eq('id',id);if(error)throw error;}
export function calculateDriverLedger(transactions=[]){const moneyCollected=transactions.filter(t=>t.type==='cash_collection').reduce((s,t)=>s+Number(t.amount||0),0);const moneyHandedOver=transactions.filter(t=>t.type==='cash_handover').reduce((s,t)=>s+Number(t.amount||0),0);const expenses=transactions.filter(t=>t.type==='expense').reduce((s,t)=>s+Number(t.amount||0),0);const commissions=transactions.filter(t=>t.type==='commission').reduce((s,t)=>s+Number(t.amount||0),0);const adjustments=transactions.filter(t=>t.type==='adjustment').reduce((s,t)=>s+Number(t.amount||0),0);return {moneyCollected,moneyHandedOver,expenses,commissions,adjustments,cashWithDriver:moneyCollected-moneyHandedOver-expenses,amountOwedToDriver:commissions+adjustments-expenses};}
export async function listDeliveryOrders({branchId=null,driverId=null,deliveryStatus=null}={}){let q=supabase.from('sales').select('*, delivery_drivers(name, phone, vehicle)').eq('order_type','delivery').order('created_at',{ascending:false});if(branchId)q=q.eq('branch_id',branchId);if(driverId)q=q.eq('delivery_driver_id',driverId);if(deliveryStatus)q=q.eq('delivery_status',deliveryStatus);const {data,error}=await q;if(error)throw error;return data||[];}
export async function updateDeliveryStatus(saleId,deliveryStatus){const {data,error}=await supabase.from('sales').update({delivery_status:deliveryStatus}).eq('id',saleId).select().single();if(error)throw error;return data;}
export async function recordDeliveryCollection({driverId,saleId,amount,branchId,createdBy}){const value=Number(amount||0);if(value<=0)throw new Error('مبلغ التحصيل يجب أن يكون أكبر من صفر');const {data:existing}=await supabase.from('driver_transactions').select('id').eq('sale_id',saleId).eq('type','cash_collection').limit(1);if(existing?.length)throw new Error('تم تسجيل تحصيل هذا الأوردر بالفعل');const {data:sale,error:saleErr}=await supabase.from('sales').select('id,total,paid_amount,delivery_driver_id,delivery_status').eq('id',saleId).single();if(saleErr)throw saleErr;if(sale.delivery_driver_id!==driverId)throw new Error('الأوردر غير مربوط بهذا المندوب');const due=Math.max(Number(sale.total||0)-Number(sale.paid_amount||0),0);if(value>due)throw new Error(`المبلغ المستحق ${due.toFixed(2)}`);const {data:tx,error:txErr}=await supabase.from('driver_transactions').insert({driver_id:driverId,type:'cash_collection',amount:value,branch_id:branchId,sale_id:saleId,description:'تحصيل من عميل دليفري',txn_date:new Date().toISOString().slice(0,10),created_by:createdBy}).select().single();if(txErr)throw txErr;const newPaid=Number(sale.paid_amount||0)+value;const {error:upErr}=await supabase.from('sales').update({paid_amount:newPaid,payment_method:'cash',delivery_status:newPaid>=Number(sale.total||0)?'delivered':'partial'}).eq('id',saleId);if(upErr)throw upErr;return tx;}
export async function recordDriverHandover({driverId,amount,branchId,createdBy,description=''}){return createDriverTransaction({driver_id:driverId,type:'cash_handover',amount:Number(amount||0),branch_id:branchId,description:description||'توريد عهدة للمحل',txn_date:new Date().toISOString().slice(0,10),created_by:createdBy});}
